language: cpp
os:
  - linux
  - osx

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - clang-3.5
      - libstdc++-4.9-dev
      - g++-4.9
      - liblua5.1-0-dev
      - lua5.1
      - libboost-dev
    sources:
      - llvm-toolchain-precise-3.5
      - ubuntu-toolchain-r-test

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install lua;
    elif [ "$CXX" == "g++"  ]; then
      export CXX="g++-4.9";
    elif [ "$CXX" == "clang++"  ]; then
      export CXX="clang++-3.5";
    fi

script:
  - export OUTSOURCE=$PWD/build
  - export SOURCEPATH=$PWD
  - mkdir -p $OUTSOURCE && cd $OUTSOURCE && cmake $SOURCEPATH && make && make install
  - cd $SOURCEPATH/bin && echo "os.exit()" | lua -l color_coded
  - cd $SOURCEPATH && rm -rf bin && mv $OUTSOURCE/clang* . && rm -rf $OUTSOURCE
  - cmake . && make && make install
  - cd $SOURCEPATH/bin && echo "os.exit()" | lua -l color_coded
  - cd $SOURCEPATH && make color_coded_test || true
